# traffic-signal-client/src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: traffic-signal-client

# TCP客户端配置
tcp:
  client:
    server-host: localhost
    server-port: 9999
    reconnect-interval: 30000
    heartbeat-interval: 60000

# 客户端配置
client:
  cross-id: "110100001"
  signal-controller-id: "110100001001"
  system-type: "UTCS"
  auto-login: true
  password: "tsc123"
  username: "tsc_client"
  data-directory: "./data"
  report-interval: 300000  # 5分钟上报一次

# 日志配置
logging:
  level:
    com.traffic: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ./logs/client.log