# traffic-signal-server/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: traffic-signal-server

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

# TCP服务器配置
tcp:
  server:
    port: 9999
    boss-threads: 1
    worker-threads: 4

# 日志配置
logging:
  level:
    com.traffic: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"